language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
    - szeles.adorjan@hotmail.com
    - gasparrobi@gmail.com
    - szrk.peter@gmail.com
    - marti.kecskemeti@gmail.com
    on_success: always
    on_failure: always
script: mvn clean install -source 1.8